spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:mysql://192.168.254.252:3306/iris
    username: mc
    password: ${IRIS_MYSQL_PASSWD}
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect